# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventoTeglo', '0002_auto_20171020_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesagem',
            name='peso',
            field=models.FloatField(max_length=6, verbose_name='peso'),
        ),
        migrations.AlterField(
            model_name='pesagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
