# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 22:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventoTeglo', '0003_auto_20171020_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesagem',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pesagem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
